Repository Azure/azure-cosmosdb-java, pull requests merged in 2019-08, with the labels that each got.

#241 2.6.0
  benchmark/pom.xml
  changelog/README.md
  commons-test-utils/pom.xml
  commons/pom.xml
  commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
  direct-impl/pom.xml
  examples/pom.xml
  gateway/pom.xml
  pom.xml
  sdk/pom.xml
Labels: release

#232 Add David to codeowners
  CODEOWNERS
Labels: engineering

#245 bugfix: try other regions on multimaster for query when the current region is unavailable
  gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/ClientRetryPolicy.java
  gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/query/DocumentProducer.java
  gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/query/QueryPlanRetriever.java
Labels: hotfix

#95 Add more prominent attribution for MurmurHash3
  README.md
Labels: documentation

#246 2.6.1
  README.md
  benchmark/pom.xml
  changelog/README.md
  commons-test-utils/pom.xml
  commons/pom.xml
  commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
  direct-impl/pom.xml
  examples/pom.xml
  gateway/pom.xml
  pom.xml
  sdk/pom.xml
Labels: release
